### ISSUE TITLE
Question for the hand/gripper control

### ISSUE THREAD

**Issue by JackTony123** [abr/abr_control#106]
Hello everyone, recently I tried this lib to implement In our robot arm simulation on Mujoco I didn't find any example for the gripper control such as Jaco2 and don't know how to do that Can anyone give some suggestions for that or share what you did for your robot simulation? Thanks!

**Comment by p3jawors** [comment]
We used to have some examples of the jaco2, but looking at the latest code it looks like its no longer there. However, it's fairly simple to add. The control signal we send, `u`, can be 9D for the jaco2. You can calculate the first 6 with one of our controllers. The last 3 are the force commands for the 3 fingers of the jaco2. You can change these values to open and close the hand, but we provide no gripper controllers in the repo. Note that if you are planning on using the real jaco2 that the gripper is position based only, but in our mujoco sims they are force based like the other actuators in the arm.

To use this feature just set the `use_joint_dyn_addrs` to `False` in the mujoco interface function call `send_forces`. You can see the docstring [here](https://github.com/abr/abr_control/blob/main/abr_control/interfaces/mujoco.py#L151). Then you just add the three force commands you want for the gripper.
