### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HaMengder** [abr/abr_control#114]
ModuleNotFoundError: No module named 'mujoco_viewer'. How to find the revelant file

**Comment by studywolf** [comment]
Ah, I need to add that to documentation of us not in there. You need to install this repo: https://github.com/rohanpsingh/mujoco-python-viewer

**Comment by HaMengder** [comment]
> 啊，我需要把它添加到我们不在那里的文档中。您需要安装此存储库：https://github.com/rohanpsingh/mujoco-python-viewer

OK，Thanks
