### ISSUE TITLE
TypeError: argument is not an mpz

### ISSUE THREAD

**Issue by niudong1001** [abr/abr_control#25]
Hi, friends, i installed abr_control and run the code below:
```
from abr_control.arms import jaco2
from abr_control.controllers import OSC
from abr_control.interfaces import VREP

robot_config = jaco2.Config()
ctrlr = OSC(robot_config)
interface = VREP(robot_config)

interface.connect()

target_xyz = [.2, .2 .5]  # in metres
for ii in range(1000)
    feedback = interface.get_feedback()  # returns a dictionary with q, dq
    u = ctrlr.generate(feedback['q'], feedback['dq'], target_xyz)
    interface.send_forces(u)  # send forces and step VREP sim forward

interface.disconnect()
```
I got this error:
`TypeError: argument is not an mpz`
Hope to find a solution~

**Comment by p3jawors** [comment]
Hi, can you please send the full stack trace, it will be make debugging a bit easier.

Cheers

**Comment by dongniu0927** [comment]
Hello, thanks for your reply, and i find the same problem  in your repo's `readme.rst` file.
I fixed that and gave a (pull)[https://github.com/abr/abr_control/pull/26].
![image](https://user-images.githubusercontent.com/25112722/40289043-c679aae0-5ce8-11e8-8aba-3d72728b4763.png)

**Comment by studywolf** [comment]
thanks for the heads up! we will correct that!
