### ISSUE TITLE
Import redis in dynamics_adaptation

### ISSUE THREAD

**Issue by p3jawors** [abr/abr_control#31]
Should set this up as an option and use a try except in the case that the user wants the functionality. At the moment you get an error if redis isn't installed, but it shouldn't be required.

**Comment by studywolf** [comment]
I think here, because redis is being used for visualization in one of our applications only and isn't used by anything else, we should remove it from `abr_control` and find a way to hack it in for that application

**Comment by studywolf** [comment]
removed in https://github.com/abr/abr_control/commit/5b033e98d07be21146656d3d193aa7ca3a427e88
