### ISSUE TITLE
Import nengo_extras in dynamics_adaptation

### ISSUE THREAD

**Issue by p3jawors** [abr/abr_control#32]
try except not set up correctly. At the moment if nengo_extras isn't installed an exception is raised at the start of the module, but this should be moved to where nengo_extras would be used. It is only required when doing bootstrap learning, which is not very often.

**Comment by studywolf** [comment]
no longer an issue with https://github.com/abr/abr_control/commit/5b033e98d07be21146656d3d193aa7ca3a427e88
