### ISSUE TITLE
3D model files missing

### ISSUE THREAD

**Issue by xuhuairuogu** [abr/abr_control#60]
Hi, I am a new user of abr_control. The examples in the directories of PyGame and VREP both work well. However, when I execute `python3 dynamics_adaptation_osc.py`, I receive the following error:
![Screenshot from 2019-10-15 14-41-52](https://user-images.githubusercontent.com/10009476/66806383-fac73d80-ef59-11e9-9c77-1cadfa3c6ecf.png)
And indeed there isn't any 3D model file in meshes directory. Where can I get jaco2's model files?

**Comment by xuhuairuogu** [comment]
I download model files from kinova-ros package and it works!

**Comment by studywolf** [comment]
Excellent! Glad you found them and it's working for you. We decided to not include the stl files, but as you found there's a comment in the xml file about where to download them. I'll make an issue to add that to the readme so it's easier to find. Cheers!
