### ISSUE TITLE
AttributeError: 'MjViewer' object has no attribute 'exit'

### ISSUE THREAD

**Issue by superggb** [abr/abr_control#61]
I have installed mujoco200 and mujoco-py2.0.
But when I run the /example/Mujoco, there is an error in this code:
'if interface.viewer.exit:'
           .......

So I can't run any Mujoco examples for all they have this code in the first 'While'.....

I have searched it online, may it be the prolem of version of mujoco-py ?
For there is not mujoco-py‘s and mujoco's version mentioned.

**Comment by studywolf** [comment]
Hi SuperGGB,

Whoops. I made some changes to mujoco-py and forgot to make them public. I'll fork the repo and post when there's a branch available here to use.
Cheers,

**Comment by studywolf** [comment]
OK I have the change up on a branch here https://github.com/studywolf/mujoco-py/tree/exit_externally_handled

You can either clone and change to this branch or you could look at the changes from the last commit and apply them locally. Please let me know if this doesn't work for you!

**Comment by superggb** [comment]
yep! this solution worked.
Thank you a lot !
