### ISSUE TITLE
ask for  reference about the controllers

### ISSUE THREAD

**Issue by vanusy** [abr/abr_control#83]
I have seen there are several different controllers in the "abr_control/abr_control/controllers/", such as OSC and sliding et al. Could you give me some references related to your controllers? Many thanks for your kindly help :-D

**Comment by studywolf** [comment]
Hello! You're referring to the OSC, right? I've added one for that controller in our open PR, and expanded the reference for the sliding controller. If there are any other questions about the others I can try to track down some references for those too! The references for sliding and OSC are 

OSC: [Khatib, Oussama. "A unified approach for motion and force control of robot manipulators: The operational space formulation." IEEE Journal on Robotics and Automation 3.1 (1987): 43-53.]
Sliding: [Slotine, Jean-Jacques E., and Weiping Li. "On the adaptive control of robot manipulators." The international journal of robotics research 6.3 (1987): 49-59.]

**Comment by vanusy** [comment]
Yes, I'm referring to the OSC. Thanks a lot for your help. :-)
















At 2020-08-12 00:01:37, "Travis DeWolf" <notifications@github.com> wrote:

Hello! You're referring to the OSC, right? I've added one for that controller in our open PR, and expanded the reference for the sliding controller. If there are any other questions about the others I can try to track down some references for those too! The references for sliding and OSC are

OSC: [Khatib, Oussama. "A unified approach for motion and force control of robot manipulators: The operational space formulation." IEEE Journal on Robotics and Automation 3.1 (1987): 43-53.]
Sliding: [Slotine, Jean-Jacques E., and Weiping Li. "On the adaptive control of robot manipulators." The international journal of robotics research 6.3 (1987): 49-59.]

**Comment by studywolf** [comment]
You're welcome!
